// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/detection/run": {
            "post": {
                "description": "Triggers one immediate drift detection cycle. Scheduler keeps running independently.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "detection"
                ],
                "summary": "Run one detection cycle manually",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.DetectionRunResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.APIError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.APIError"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns service liveness state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.HealthResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns readiness state based on successful detection cycle execution.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ReadinessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "drift-detector-svc_internal_domain.DetectionStats": {
            "type": "object",
            "properties": {
                "comparedHosts": {
                    "type": "integer"
                },
                "desiredHosts": {
                    "type": "integer"
                },
                "driftsFound": {
                    "type": "integer"
                },
                "errors": {
                    "type": "integer"
                },
                "reconcileSent": {
                    "type": "integer"
                },
                "reconcileSuppressed": {
                    "type": "integer"
                },
                "skippedHostsNoActualData": {
                    "type": "integer"
                },
                "skippedHostsNoActualHost": {
                    "type": "integer"
                }
            }
        },
        "internal_transport_http.APIError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "detection cycle already running"
                }
            }
        },
        "internal_transport_http.DetectionCycleDTO": {
            "type": "object",
            "properties": {
                "cycleId": {
                    "type": "string"
                },
                "durationMs": {
                    "type": "integer"
                },
                "errorMessages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "finishedAt": {
                    "type": "string"
                },
                "inventoryMarkedPartial": {
                    "type": "boolean"
                },
                "parserReady": {
                    "type": "boolean"
                },
                "partial": {
                    "type": "boolean"
                },
                "startedAt": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/drift-detector-svc_internal_domain.DetectionStats"
                },
                "trigger": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_transport_http.DetectionRunResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/internal_transport_http.DetectionCycleDTO"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "internal_transport_http.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_transport_http.ReadinessResponse": {
            "type": "object",
            "properties": {
                "lastCycleAt": {
                    "type": "string"
                },
                "lastCycleId": {
                    "type": "string"
                },
                "lastCyclePartial": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "DriftDetectorSvc API",
	Description:      "DriftDetectorSvc compares desired and actual host state, detects workload drift, and sends asynchronous reconcile commands.\n\nMVP supported components:\n- node_exporter\n- cadvisor",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
