run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-generated: strict

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - typecheck
    - unused
    - revive
    - misspell
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
